/* KOJI — content (both languages). Prices/availability come live from Supabase (products table);
   the prices here are only a fallback if the API is unreachable.
   Price source: 06_BUSINESS/02_MARKET_AND_PRICING/KOJI_BLACK_GARLIC_PRICE_SURVEY_2026-10-03.md (v28). */
window.KOJI = window.KOJI || {};

KOJI.CITIES = [
  ["cairo", "القاهرة", "Cairo"], ["giza", "الجيزة", "Giza"], ["alex", "الإسكندرية", "Alexandria"],
  ["qalyubia", "القليوبية", "Qalyubia"], ["sharqia", "الشرقية", "Sharqia"], ["dakahlia", "الدقهلية", "Dakahlia"],
  ["gharbia", "الغربية", "Gharbia"], ["monufia", "المنوفية", "Monufia"], ["beheira", "البحيرة", "Beheira"],
  ["other", "محافظة تانية", "Other governorate"],
];
KOJI.KG = [["lt_half", "أقل من نص كيلو", "Under 0.5 kg"], ["half_1", "من نص كيلو لكيلو", "0.5–1 kg"], ["1_3", "من ١ لـ٣ كيلو", "1–3 kg"], ["gt_3", "أكتر من ٣ كيلو", "Over 3 kg"], ["unknown", "مش عارف لسه", "Not sure yet"]];
KOJI.STATUS = {
  new: ["استلمنا طلبك", "Order received"], confirmed: ["اتأكد", "Confirmed"], out_for_delivery: ["خرج للتوصيل", "Out for delivery"],
  delivered: ["اتسلّم", "Delivered"], cancelled: ["اتلغى", "Cancelled"],
};

KOJI.T = {
ar:{
  "title.home":"كوجي — ثوم أسود متعتّق في مصر","title.shop":"المتجر — كوجي","title.recipes":"وصفات — كوجي","title.story":"الحكاية — كوجي","title.chefs":"للمطاعم — كوجي","title.track":"تتبّع طلبك — كوجي","title.privacy":"الخصوصية — كوجي","title.terms":"الشروط والتوصيل — كوجي","title.404":"الصفحة مش موجودة — كوجي",
  "bar":["طلب مسبق: بنأكد ميعاد التسليم قبل أي دفع","مكوّن واحد · ٢١ يوم · من غير إضافات","صنع في مصر"],
  "nav.shop":"المتجر","nav.story":"الحكاية","nav.recipes":"وصفات","nav.chefs":"للمطاعم","nav.cart":"السلة","nav.home":"الرئيسية","nav.track":"تتبّع طلبك",
  "loader":"بنعتّق","scroll":"انزل",
  "hero.h":"ثوم،<br><i>اديناله وقته.</i>","hero.p":"ثوم مصري بيتعتّق ٢١ يوم لحد ما يسودّ ويطرى، ويبقى طعمه حلو ومالح زي البلسميك.","hero.cta":"تسوّق",
  "mani.big":"مكوّن واحد. ٢١ يوم. ولا حاجة تانية. الحرارة الهادية بتخلّي السكر والبروتين اللي في الثوم يتفاعلوا ببطء، فالحدة بتروح، ويفضل طعم عميق مالوش اسم في المطبخ المصري لسه.",
  "mani.sub":"بنعتّق على دفعات صغيرة. من غير تخمير، ولا سكر مضاف، ولا مواد حافظة. وقت وحرارة هادية وبس.",
  "mani.cta":"اعرف الحكاية",
  "label.h":"على العبوة","label.ing":"المكوّنات","label.ingv":"ثوم ١٠٠٪","label.aged":"مدة التعتيق","label.agedv":"٢١ يوم","label.origin":"المنشأ","label.originv":"مصر","label.sugar":"سكر مضاف","label.pres":"مواد حافظة","label.none":"مفيش","label.keep":"الحفظ","label.keepv":"مكان بارد وناشف",
  "days.k":"٢١ يوم في دقيقة سكرول","days.unit":"يوم",
  "d0.h":"ثوم مصري طازج","d0.p":"بصل كامل، أبيض وحاد زي أي ثوم.",
  "d1.h":"بيبدأ يغمق","d1.p":"الفص بياخد لون عسلي، والحدة بتبدأ تهدى.",
  "d2.h":"الحلاوة بتطلع","d2.p":"بني غامق، وطعم كراميل وفواكه مجففة.",
  "d3.h":"أسود وطري","d3.p":"طري زي التمر. حلو ومالح، وفيه حموضة خفيفة.",
  "hero.what":"يعني إيه ثوم أسود؟","about.k":"إيه هو","about.h":"ثوم مصري،<br><i>اتعتّق ٢١ يوم.</i>","pts.1b":"١","pts.1":"مكوّن واحد: ثوم","pts.2b":"٢١","pts.2":"يوم تعتيق على حرارة هادية","pts.3b":"٠","pts.3":"سكر مضاف أو مواد حافظة",
  "home.range":"منتجاتنا","home.all":"كل المنتجات",
  "shop.h":"منتجاتنا","shop.p":"فصوص، ومعجون، وبصل كامل. كله من دفعات صغيرة، ومن غير أي إضافات.",
  "f.all":"الكل","f.kitchen":"للمطبخ","f.gift":"هدايا","f.daily":"يومي",
  "shop.note":"مصاريف التوصيل بتتحدد حسب العنوان، وبنأكدها معاك قبل أي دفع",
  "add":"أضف للسلة","added":"اتضاف ✓","view":"شوف","soldout":"خلصت الكمية",
  "taste.k":"بروفايل الطعم","taste.h":"مش ثوم.<br>ومش حلو.","taste.p":"أقرب حاجة ليه تمرة فيها لمسة بلسميك وصويا. طري ومطاطي، وبيدوب في الصوص السخن.",
  "taste.black":"ثوم أسود","taste.fresh":"ثوم طازج","taste.note":"تقدير من تذوقنا للثوم الأسود، مش قياس معملي.",
  "fact.sweet":"حلاوة","fact.umami":"أومامي","fact.bals":"بلسمي","fact.acid":"حموضة","fact.bite":"حدّة",
  "ways.h":"تلات طرق تبدأ بيها",
  "w1.h":"افرده","w1.p":"اهرس فص على توست أو مع جبنة، أو استخدم المعجون على طول.","w1.d":"فص واحد · حوالي ٢ جم",
  "w2.h":"دوّبه","w2.p":"في صوص سخن، أو مكرونة، أو زبدة على ستيك طالع من على النار.","w2.d":"٢–٣ فصوص",
  "w3.h":"اخفقه","w3.p":"مع مايونيز، أو طحينة، أو عسل وصويا يبقى جليز.","w3.d":"معلقة صغيرة معجون",
  "rec.h":"وصفات","rec.k":"من المطبخ المصري","rec.all":"كل الوصفات","rec.p":"وصفات بسيطة بحاجات موجودة في أي مطبخ مصري. اختار واحدة واطبخها النهارده.",
  "rc.all":"الكل","rc.breakfast":"فطار","rc.main":"أطباق رئيسية","rc.sauce":"صوصات وتتبيلات",
  "r.ing":"المكوّنات","r.steps":"الطريقة","r.time":"الوقت","r.serves":"يكفي","r.uses":"بيستخدم","r.next":"الوصفة الجاية","r.tick":"علّم على اللي جهزته",
  "chefs.k":"للمطاعم والشيفات","chefs.h":"بالكيلو،<br><i>لمطبخك.</i>","chefs.p":"فصوص مقشّرة في كيس حاجز، ومعجون، وبصل كامل. دي أسعار الكيلو، وبنأكد السعر النهائي والكميات مع أول طلب.",
  "chefs.l1":"عينة لطبق واحد قبل أول طلب","chefs.l2":"فصوص مقشّرة، من غير وقت تحضير ولا هدر","chefs.l3":"الكميات ومواعيد التوريد بنتفق عليها مع كل مطبخ","chefs.cta":"اطلب عينة","chefs.req":"اطلب","chefs.more":"صفحة المطاعم",
  "chefs.ph":"بالكيلو، لمطبخك.","chefs.pp":"بنشتغل مع المطابخ بنفس طريقة الشيف: نجرّب في طبق حقيقي، ونقارن، والطبق هو اللي يقرر.",
  "chefs.price":"أسعار الكيلو","chefs.how":"إزاي بنبدأ","chefs.ctah":"جرّبه في طبق<br><i>من المنيو بتاعك.</i>","chefs.ctap":"بنبعتلك عينة، تقارنها بالطبق العادي، وإنت تقرر.",
  "s1.h":"نختار الطبق","s1.p":"وصفة موجودة عندك، وفرصة نكهة محددة.","s2.h":"نحدد المقارنة","s2.p":"المورد الحالي أو طريقتك الحالية.","s3.h":"نجرّب كميتين","s3.p":"٢ جم و٥ جم في نفس الطبق: الطعم، والقوام، وسهولة الاستخدام.","s4.h":"إنت تقرر","s4.p":"ترفض، أو نعدّل، أو نبدأ طلب تجاري.",
  "story.h":"الحكاية","story.p":"تلات شركا، وغرفة تعتيق صممناها بنفسنا، وسؤال واحد: ليه الثوم الأسود مش في مطبخنا؟",
  "story.big":"الثوم الأسود مكوّن معروف في كوريا واليابان من سنين. ومصر من أكبر الدول المنتجة للثوم في العالم، ومع ذلك لسه مش موجود في أغلب المطابخ المصرية. فقررنا نعتّقه هنا.",
  "story.vh":"اللي ماشيين عليه",
  "v1.h":"مكوّن واحد","v1.p":"ثوم وبس. مفيش سكر، ولا مواد حافظة، ولا ألوان.","v2.h":"كل دفعة ليها رقم","v2.p":"بنسجّل كل دفعة، ورقمها بيتكتب على العبوة، عشان أي ملاحظة توصل لمصدرها.","v3.h":"صنع في مصر","v3.p":"ثوم مصري، وغرفة تعتيق من تصميمنا بتتصنع في ورشة مصرية.","v4.h":"أكل، مش علاج","v4.p":"مش هنقول ادعاءات صحية من غير دليل على منتجنا نفسه.",
  "faq.h":"أسئلة",
  "cta.h":"جرّبه في<br><i>طبق واحد.</i>","cta.p":"ابدأ ببرطمان فصوص، وجرّبه في أي طبق بتحط فيه ثوم أو صويا أو بلسميك.","cta.btn":"تسوّق الفصوص",
  "pdp.pair":"اطبخ بيه","pdp.more":"منتجات تانية","pdp.use":"إزاي تستخدمه","pdp.keep":"الحفظ","pdp.ship":"التوصيل والدفع",
  "pdp.shipv":"القاهرة والجيزة الأول. مصاريف التوصيل بتتحدد حسب العنوان، وبنقولهالك قبل التأكيد. الدفع كاش عند الاستلام، أو إنستاباي، أو فودافون كاش، ومفيش أي دفع قبل ما نأكد ميعاد التسليم.",
  "pd.pack":"العبوة","pd.ing":"المكوّنات","pd.ingv":"ثوم ١٠٠٪","pd.use":"بيتاكل مع",
  "ft.line":"ثوم أسود بيتعتّق في مصر، دفعة دفعة.","ft.shop":"المتجر","ft.help":"مساعدة","ft.faq":"أسئلة شائعة","ft.contact":"تواصل","ft.privacy":"الخصوصية","ft.terms":"الشروط والتوصيل",
  "ft.copy":"© ٢٠٢٦ كوجي","ft.illus":"بعض الصور توضيحية لحد ما نصوّر دفعاتنا",
  "cart.h":"سلتك","cart.empty":"السلة فاضية","cart.emptyp":"ابدأ ببرطمان فصوص.","cart.go":"روح للمتجر","cart.items":"المنتجات","cart.ship":"التوصيل","cart.shipv":"بيتحدد حسب العنوان","cart.total":"الإجمالي","cart.co":"كمّل الطلب","cart.rm":"شيل","cart.closed":"الطلبات مقفولة مؤقتًا. جرّب تاني قريب.",
  "co.k":"إتمام الطلب","co.h":"آخر خطوة","co.p":"ده طلب مسبق: هنكلمك نأكد ميعاد التسليم ومصاريف التوصيل قبل أي دفع.","co.pnp":"هنكلمك نأكد الطلب ومصاريف التوصيل قبل التسليم.",
  "co.tk":"عينة للمطاعم","co.th":"جرّب كوجي في مطبخك","co.tp":"قولّنا المطعم والطبق، وهنتواصل معاك نحدد ميعاد العينة.",
  "co.name":"الاسم","co.phone":"رقم الموبايل","co.city":"المحافظة","co.area":"المنطقة","co.addr":"العنوان بالتفصيل","co.addrph":"الشارع، رقم العمارة، الدور، الشقة","co.venue":"المطعم","co.role":"دورك","co.dish":"الطبق اللي عايز تجرّبه فيه","co.product":"المنتج","co.anyproduct":"مش متأكد","co.kg":"تتوقع تستخدم كام في الشهر؟","co.notes":"ملاحظات (اختياري)","co.pay":"طريقة الدفع",
  "co.cod":"كاش عند الاستلام","co.codd":"بتدفع للمندوب","co.insta":"إنستاباي","co.instad":"بنبعتلك بيانات التحويل بعد التأكيد","co.vf":"فودافون كاش","co.vfd":"بنبعتلك الرقم بعد التأكيد",
  "co.sum":"الإجمالي (من غير التوصيل)","co.fee":"التوصيل","co.submit":"أكّد الطلب","co.tsubmit":"ابعت الطلب","co.sending":"بنبعت...","co.consent":"بالضغط على تأكيد إنت موافق على","co.terms":"الشروط","co.and":"و","co.privacy":"سياسة الخصوصية",
  "co.req":"مطلوب","co.badphone":"رقم موبايل مصري غير صحيح",
  "err.closed":"الطلبات مقفولة مؤقتًا.","err.bad_phone":"رقم الموبايل مش صحيح.","err.bad_name":"اكتب اسمك.","err.bad_address":"اكتب العنوان بالتفصيل.","err.bad_venue":"اكتب اسم المطعم.","err.bad_product":"منتج في السلة مبقاش متاح. شيله وجرّب تاني.","err.rate_limited":"بعتّ طلبات كتير من نفس الرقم. استنى شوية وجرّب تاني.","err.network":"مقدرناش نوصل للسيرفر. اتأكد من النت وجرّب تاني.","err.generic":"حصلت مشكلة. جرّب تاني.",
  "done.h":"طلبك وصلنا","done.th":"طلبك وصلنا","done.code":"رقم الطلب","done.p":"هنكلمك على","done.p2":"خلال يوم عمل، نأكد ميعاد التسليم ومصاريف التوصيل. احتفظ برقم الطلب عشان تتابعه.","done.tp":"هنكلمك نحدد ميعاد العينة.","done.track":"تتبّع الطلب","done.more":"كمّل تسوّق","done.ok":"تمام",
  "track.h":"تتبّع طلبك","track.p":"اكتب رقم الطلب ورقم الموبايل اللي طلبت بيه.","track.code":"رقم الطلب","track.btn":"تتبّع","track.nf":"مالقيناش طلب بالبيانات دي. اتأكد من رقم الطلب ورقم الموبايل.","track.fee":"التوصيل","track.feetbd":"بيتحدد","track.total":"الإجمالي","track.payto":"حوّل على","track.placed":"اتطلب",
  "roles":["شيف","صاحب المطعم / مدير","مشتريات","غير كده"],
  "toast.add":"اتضاف للسلة",
  "privacy.p":"إيه اللي بنجمعه لما تطلب، وبنستخدمه في إيه، ومين يقدر يشوفه.","terms.p":"الطلب المسبق، والأسعار، والتوصيل، والدفع، والإلغاء، والاسترجاع.",
  "404.h":"الصفحة دي<br><i>مش موجودة.</i>","404.p":"يمكن اللينك اتغيّر. جرّب المتجر أو الرئيسية.",
  
  "desc.home":"ثوم مصري متعتّق ٢١ يوم لحد ما يسودّ ويطرى. فصوص ومعجون وبصل كامل، مكوّن واحد ومن غير إضافات. اطلب أونلاين، ومفيش دفع قبل التأكيد.",
  "desc.shop":"فصوص ثوم أسود، ومعجون، وبصل كامل، وطقم هدية. ثوم مصري متعتّق ٢١ يوم، من غير سكر مضاف ولا مواد حافظة.",
  "desc.recipes":"وصفات بسيطة بالثوم الأسود من المطبخ المصري: طحينة، ومكرونة وايت صوص، وفراخ في الفرن، وتوست بالجبنة.",
  "desc.story":"تلات شركا، وغرفة تعتيق صممناها بنفسنا، وسؤال واحد: ليه الثوم الأسود مش في مطبخنا؟",
  "desc.chefs":"ثوم أسود بالكيلو للمطاعم في مصر: فصوص مقشّرة، ومعجون، وبصل كامل. اطلب عينة لطبق واحد قبل أول طلب.",
  "desc.track":"تابع طلبك من كوجي برقم الطلب ورقم الموبايل.","desc.privacy":"إيه اللي بنجمعه لما تطلب من كوجي، وبنستخدمه في إيه.","desc.terms":"الطلب المسبق، والأسعار، والتوصيل، والدفع، والإلغاء، والاسترجاع في كوجي.","desc.404":"الصفحة دي مش موجودة.",
  "soon":"متاح قريبًا","bar.closed":"الطلبات هتفتح قريب، والمطاعم تقدر تطلب عينة دلوقتي",
  "nav.menu":"القائمة","kick.hero":"ثوم أسود · متعتّق في مصر",
  "mq":["مكوّن واحد","٢١ يوم تعتيق","من غير سكر مضاف","من غير مواد حافظة","ثوم مصري","دفعات صغيرة"],
  "shop.k":"المتجر","about.not.h":"مش مخمّر، ولا فيه فطر.","about.not.p":"اللون الأسود من تفاعل ميلارد: السكر والبروتين اللي في الثوم بيتفاعلوا ببطء مع الحرارة الهادية، زي العيش لما يتحمّص.",
  "days.h":"من أبيض لأسود في ٢١ يوم","days.day":"يوم",
  "ways.k":"إزاي تستخدمه","rec.home":"وصفات من<br><i>المطبخ المصري.</i>",
  "pr.k":"إزاي بنشتغل","pr.h":"اطلب وإنت مطمّن.",
  "pr1.h":"مفيش دفع قبل التأكيد","pr1.p":"بنكلمك نأكد ميعاد التسليم ومصاريف التوصيل الأول.",
  "pr2.h":"ادفع زي ما تحب","pr2.p":"كاش عند الاستلام، أو إنستاباي، أو فودافون كاش.",
  "pr3.h":"مكوّن واحد","pr3.p":"ثوم ١٠٠٪. من غير سكر مضاف ولا مواد حافظة.",
  "pr4.h":"تابع طلبك","pr4.p":"برقم الطلب ورقم موبايلك، في أي وقت.",
  "guide.k":"مش عارف تختار؟","guide.h":"فصوص، ولا معجون،<br><i>ولا بصل كامل؟</i>",
  "g.cloves":"للتقطيع والأكل زي ما هو. أسهل بداية.","g.paste":"بيتخلط في الصوصات والتتبيلات من غير هرس.","g.bulbs":"للتقديم والهدايا. بتقشّره وقت ما تحتاجه.",
  "pdp.badges":["ثوم ١٠٠٪","٢١ يوم تعتيق","من غير إضافات"],"pdp.pre":"طلب مسبق: بنأكد معاك قبل أي دفع","pdp.photo":"صورة",
  "story.team.h":"مين إحنا","story.team.p":"تلات شركا درسنا هندسة كيميائية. بنعتّق الثوم بنفس الطريقة اللي اتعلمنا نشتغل بيها: نقيس، ونسجّل، ونجرّب تاني لحد ما الطعم يبقى مظبوط.",
  "cart.up":"ضيف معاه","cart.note":"مفيش دفع دلوقتي. هنكلمك نأكد الأول.",
},
en:{
  "title.home":"KOJI — Black Garlic, Aged in Egypt","title.shop":"Shop — KOJI","title.recipes":"Recipes — KOJI","title.story":"Our Story — KOJI","title.chefs":"For Chefs — KOJI","title.track":"Track your order — KOJI","title.privacy":"Privacy — KOJI","title.terms":"Terms & Delivery — KOJI","title.404":"Page not found — KOJI",
  "bar":["Pre-order: we confirm delivery before any payment","One ingredient · 21 days · nothing added","Made in Egypt"],
  "nav.shop":"Shop","nav.story":"Story","nav.recipes":"Recipes","nav.chefs":"For Chefs","nav.cart":"Bag","nav.home":"Home","nav.track":"Track order",
  "loader":"Ageing","scroll":"Scroll",
  "hero.h":"Garlic,<br><i>given time.</i>","hero.p":"Egyptian garlic, aged for 21 days until it turns black, soft and sweet-savory, like balsamic.","hero.cta":"Shop the range",
  "mani.big":"One ingredient. Twenty-one days. Nothing else. Gentle heat lets the garlic's own sugars and amino acids react slowly; the bite fades, and what's left is a depth the pantry has no other word for.",
  "mani.sub":"Aged in small lots. No fermentation, no added sugar, no preservatives. Just time and gentle heat.",
  "mani.cta":"Read our story",
  "label.h":"On the label","label.ing":"Ingredients","label.ingv":"Garlic, 100%","label.aged":"Aged","label.agedv":"21 days","label.origin":"Origin","label.originv":"Egypt","label.sugar":"Added sugar","label.pres":"Preservatives","label.none":"None","label.keep":"Storage","label.keepv":"Cool, dry place",
  "days.k":"21 days in one scroll","days.unit":"days",
  "d0.h":"Fresh Egyptian garlic","d0.p":"Whole bulbs, white and sharp like any garlic.",
  "d1.h":"It starts to darken","d1.p":"The cloves turn honey-coloured and the bite begins to soften.",
  "d2.h":"Sweetness arrives","d2.p":"Deep brown, with notes of caramel and dried fruit.",
  "d3.h":"Black and tender","d3.p":"Soft like a date. Sweet, savory, gently tart.",
  "hero.what":"What is black garlic?","about.k":"What it is","about.h":"Egyptian garlic,<br><i>aged 21 days.</i>","pts.1b":"1","pts.1":"ingredient: garlic","pts.2b":"21","pts.2":"days of gentle ageing","pts.3b":"0","pts.3":"added sugar or preservatives",
  "home.range":"Our products","home.all":"All products",
  "shop.h":"Our products","shop.p":"Cloves, paste and whole bulbs. All from small lots, with nothing added.",
  "f.all":"All","f.kitchen":"Kitchen","f.gift":"Gifts","f.daily":"Daily",
  "shop.note":"Delivery is quoted by address and confirmed with you before any payment",
  "add":"Add to bag","added":"Added ✓","view":"View","soldout":"Sold out",
  "taste.k":"Flavor profile","taste.h":"Not garlic.<br>Not sweet.","taste.p":"Closest to a date with a touch of balsamic and soy. Soft and chewy, and it melts into a hot sauce.",
  "taste.black":"Black garlic","taste.fresh":"Fresh garlic","taste.note":"Our tasting estimate for black garlic, not a lab measurement.",
  "fact.sweet":"Sweetness","fact.umami":"Umami","fact.bals":"Balsamic","fact.acid":"Acidity","fact.bite":"Bite",
  "ways.h":"Three ways in",
  "w1.h":"Spread","w1.p":"Mash a clove onto toast or with cheese, or use the paste straight.","w1.d":"1 clove · about 2 g",
  "w2.h":"Melt","w2.p":"Into a hot sauce, a pasta, or butter on a steak straight off the heat.","w2.d":"2–3 cloves",
  "w3.h":"Whisk","w3.p":"With mayonnaise, tahini, or honey and soy for a glaze.","w3.d":"1 tsp paste",
  "rec.h":"Recipes","rec.k":"From the Egyptian kitchen","rec.all":"All recipes","rec.p":"Simple recipes from an everyday Egyptian pantry. Pick one and cook it tonight.",
  "rc.all":"All","rc.breakfast":"Breakfast","rc.main":"Mains","rc.sauce":"Sauces & dressings",
  "r.ing":"Ingredients","r.steps":"Method","r.time":"Time","r.serves":"Serves","r.uses":"Uses","r.next":"Next recipe","r.tick":"Tick off what you've prepped",
  "chefs.k":"For restaurants","chefs.h":"By the kilo,<br><i>for your line.</i>","chefs.p":"Peeled cloves in barrier bags, paste and whole bulbs. Prices per kilo; we confirm final pricing and volumes with your first order.",
  "chefs.l1":"A one-dish trial before your first order","chefs.l2":"Peeled cloves: no prep time, no waste","chefs.l3":"Volumes and delivery schedule agreed with each kitchen","chefs.cta":"Request a trial","chefs.req":"Request","chefs.more":"For chefs",
  "chefs.ph":"By the kilo, for your line.","chefs.pp":"We work with kitchens the way chefs do: test it in a real dish, compare, and let the plate decide.",
  "chefs.price":"Kilo prices","chefs.how":"How we start","chefs.ctah":"Test it in a dish<br><i>already on your menu.</i>","chefs.ctap":"We send a sample, you compare it with the usual plate, and you decide.",
  "s1.h":"Pick the dish","s1.p":"A recipe already on your menu, and one flavor opportunity.","s2.h":"Set the benchmark","s2.p":"Your current supplier or in-house method.","s3.h":"Test two doses","s3.p":"2 g and 5 g in the same dish: taste, texture and handling.","s4.h":"You decide","s4.p":"Reject, revise, or start a commercial order.",
  "story.h":"Our story","story.p":"Three partners, an ageing chamber we designed ourselves, and one question: why isn't black garlic in our kitchens?",
  "story.big":"Black garlic has been a staple in Korea and Japan for years. Egypt is one of the world's largest garlic producers, yet black garlic is still missing from most Egyptian kitchens. So we decided to age it here.",
  "story.vh":"What we hold to",
  "v1.h":"One ingredient","v1.p":"Garlic. No sugar, no preservatives, no colour.","v2.h":"Every lot numbered","v2.p":"We record every lot and print its number on the pack, so any feedback reaches its source.","v3.h":"Made in Egypt","v3.p":"Egyptian garlic, and an ageing chamber of our own design, built in an Egyptian workshop.","v4.h":"Food, not medicine","v4.p":"No health claims without evidence on our own product.",
  "faq.h":"Questions",
  "cta.h":"Try it in<br><i>one dish.</i>","cta.p":"Start with a jar of cloves and try it anywhere you'd reach for garlic, soy or balsamic.","cta.btn":"Shop the cloves",
  "pdp.pair":"Cook it in","pdp.more":"More from KOJI","pdp.use":"How to use it","pdp.keep":"Storage","pdp.ship":"Delivery & payment",
  "pdp.shipv":"Cairo and Giza first. Delivery is quoted by address and confirmed before you commit. Cash on delivery, InstaPay or Vodafone Cash, and no payment before we confirm your delivery date.",
  "pd.pack":"Pack","pd.ing":"Ingredients","pd.ingv":"Garlic, 100%","pd.use":"Use with",
  "ft.line":"Black garlic, aged in Egypt, one lot at a time.","ft.shop":"Shop","ft.help":"Help","ft.faq":"FAQ","ft.contact":"Contact","ft.privacy":"Privacy","ft.terms":"Terms & delivery",
  "ft.copy":"© 2026 KOJI","ft.illus":"Some images are illustrative until we photograph our own lots",
  "cart.h":"Your bag","cart.empty":"Your bag is empty","cart.emptyp":"Start with a jar of cloves.","cart.go":"Go to the shop","cart.items":"Subtotal","cart.ship":"Delivery","cart.shipv":"Quoted by address","cart.total":"Total","cart.co":"Checkout","cart.rm":"Remove","cart.closed":"Orders are paused for now. Please check back soon.",
  "co.k":"Checkout","co.h":"Almost there","co.p":"This is a pre-order: we'll call to confirm the delivery date and fee before any payment.","co.pnp":"We'll call to confirm your order and delivery fee before delivery.",
  "co.tk":"Restaurant trial","co.th":"Try KOJI on your line","co.tp":"Tell us the restaurant and the dish, and we'll set up a trial.",
  "co.name":"Name","co.phone":"Mobile","co.city":"Governorate","co.area":"Area","co.addr":"Full address","co.addrph":"Street, building, floor, flat","co.venue":"Restaurant","co.role":"Your role","co.dish":"Dish you'd like to test it in","co.product":"Product","co.anyproduct":"Not sure","co.kg":"How much would you use per month?","co.notes":"Notes (optional)","co.pay":"Payment",
  "co.cod":"Cash on delivery","co.codd":"Pay the courier","co.insta":"InstaPay","co.instad":"Transfer details sent after confirmation","co.vf":"Vodafone Cash","co.vfd":"Number sent after confirmation",
  "co.sum":"Total (before delivery)","co.fee":"Delivery","co.submit":"Place order","co.tsubmit":"Send request","co.sending":"Sending...","co.consent":"By placing the order you agree to our","co.terms":"terms","co.and":"and","co.privacy":"privacy policy",
  "co.req":"Required","co.badphone":"Enter a valid Egyptian mobile number",
  "err.closed":"Orders are paused for now.","err.bad_phone":"That mobile number isn't valid.","err.bad_name":"Please enter your name.","err.bad_address":"Please enter your full address.","err.bad_venue":"Please enter the restaurant name.","err.bad_product":"An item in your bag is no longer available. Remove it and try again.","err.rate_limited":"Too many orders from this number. Please wait a little and try again.","err.network":"We couldn't reach the server. Check your connection and try again.","err.generic":"Something went wrong. Please try again.",
  "done.h":"Order received","done.th":"Request received","done.code":"Order number","done.p":"We'll call you on","done.p2":"within one working day to confirm the delivery date and fee. Keep your order number to track it.","done.tp":"We'll call you to schedule the trial.","done.track":"Track order","done.more":"Keep shopping","done.ok":"Done",
  "track.h":"Track your order","track.p":"Enter your order number and the mobile you ordered with.","track.code":"Order number","track.btn":"Track","track.nf":"We couldn't find an order with those details. Check the order number and mobile.","track.fee":"Delivery","track.feetbd":"To be confirmed","track.total":"Total","track.payto":"Transfer to","track.placed":"Placed",
  "roles":["Chef","Owner / GM","Purchasing","Other"],
  "toast.add":"Added to bag",
  "privacy.p":"What we collect when you order, what we use it for, and who can see it.","terms.p":"Pre-orders, prices, delivery, payment, cancellation and returns.",
  "404.h":"This page<br><i>doesn't exist.</i>","404.p":"The link may have changed. Try the shop or the home page.",
  
  "desc.home":"Egyptian garlic aged 21 days until it turns black and soft. Cloves, paste and whole bulbs: one ingredient, nothing added. Order online; no payment before we confirm.",
  "desc.shop":"Black garlic cloves, paste, whole bulbs and a gift set. Egyptian garlic aged 21 days, with no added sugar or preservatives.",
  "desc.recipes":"Simple black garlic recipes from the Egyptian kitchen: tahini, white-sauce pasta, oven chicken and cheese toast.",
  "desc.story":"Three partners, an ageing chamber we designed ourselves, and one question: why isn't black garlic in our kitchens?",
  "desc.chefs":"Black garlic by the kilo for restaurants in Egypt: peeled cloves, paste and whole bulbs. Request a one-dish trial before your first order.",
  "desc.track":"Track your KOJI order with your order number and mobile.","desc.privacy":"What KOJI collects when you order, and how it is used.","desc.terms":"Pre-orders, prices, delivery, payment, cancellation and returns at KOJI.","desc.404":"This page doesn't exist.",
  "soon":"Coming soon","bar.closed":"Orders open soon. Restaurants can request a sample now",
  "nav.menu":"Menu","kick.hero":"Black garlic · Aged in Egypt",
  "mq":["One ingredient","Aged 21 days","No added sugar","No preservatives","Egyptian garlic","Small lots"],
  "shop.k":"The shop","about.not.h":"Not fermented. No mould.","about.not.p":"The colour comes from the Maillard reaction: the garlic's own sugars and amino acids react slowly under gentle heat, the way bread browns into toast.",
  "days.h":"White to black in 21 days","days.day":"Day",
  "ways.k":"How to use it","rec.home":"Recipes from<br><i>the Egyptian kitchen.</i>",
  "pr.k":"How ordering works","pr.h":"Order with confidence.",
  "pr1.h":"No payment before we confirm","pr1.p":"We call to confirm the delivery date and fee first.",
  "pr2.h":"Pay your way","pr2.p":"Cash on delivery, InstaPay or Vodafone Cash.",
  "pr3.h":"One ingredient","pr3.p":"100% garlic. No added sugar or preservatives.",
  "pr4.h":"Track your order","pr4.p":"With your order number and mobile, any time.",
  "guide.k":"Not sure where to start?","guide.h":"Cloves, paste,<br><i>or whole bulbs?</i>",
  "g.cloves":"To slice or eat as is. The easiest start.","g.paste":"Stirs into sauces and marinades, no mashing.","g.bulbs":"For serving and gifting. Peel as you go.",
  "pdp.badges":["100% garlic","Aged 21 days","Nothing added"],"pdp.pre":"Pre-order: we confirm with you before any payment","pdp.photo":"Photo",
  "story.team.h":"Who we are","story.team.p":"Three partners who studied chemical engineering. We age garlic the way we were taught to work: measure, record, and try again until the taste is right.",
  "cart.up":"Pairs well with","cart.note":"Nothing to pay now. We'll call to confirm first.",
}};

KOJI.PRODUCTS = [
  {id:"cloves-100",slug:"black-garlic-cloves",gal:["assets/shot-cloves.webp","assets/shot-macro.webp"],cat:["kitchen","gift"],bg:"#3a2230",img:"assets/shot-cloves.webp",price:425,pair:["toast","pasta","butter"],
   ar:{n:"فصوص ثوم أسود",s:"برطمان إزاز · ١٠٠ جم",tag:"ابدأ بيه",d:"فصوص مقشّرة جاهزة للأكل في برطمان إزاز بغطا بامبو. الشكل اللي بيبدأ بيه أغلب الناس: تقطّعه، أو تهرسه، أو تاكله زي ما هو.",u:"توست بالجبنة، مكرونة، زبدة",k:"مكان بارد وناشف. بعد الفتح في التلاجة.",how:"قطّع فص وحطه على توست بجبنة، أو اهرس ٣ فصوص في زبدة طرية، أو دوّبهم في صوص سخن آخر دقيقة."},
   en:{n:"Black Garlic Cloves",s:"Glass jar · 100 g",tag:"Start here",d:"Peeled, ready-to-eat cloves in a glass jar with a bamboo lid. Where most people start: slice it, mash it, or eat it as is.",u:"Cheese toast, pasta, butter",k:"Cool, dry place. Refrigerate after opening.",how:"Slice a clove onto toast with cheese, mash three into soft butter, or melt them into a hot sauce at the last minute."}},
  {id:"paste-100",slug:"black-garlic-paste",gal:["assets/shot-paste.webp","assets/shot-macro.webp"],cat:["kitchen"],bg:"#1d1714",img:"assets/shot-paste.webp",price:375,pair:["tahini","chicken","salad"],
   ar:{n:"معجون ثوم أسود",s:"برطمان إزاز · ١٠٠ جم",d:"ثوم أسود مهروس ناعم من غير أي إضافات. أسرع طريقة تدخّله في الأكل.",u:"طحينة، تتبيلة فراخ، سلطة",k:"في التلاجة بعد الفتح، واستخدم معلقة نضيفة.",how:"معلقة صغيرة في الطحينة، أو في تتبيلة الفراخ قبل الفرن، أو في صوص المكرونة."},
   en:{n:"Black Garlic Paste",s:"Glass jar · 100 g",d:"Smooth black garlic, nothing added. The fastest way into any dish.",u:"Tahini, chicken marinades, salads",k:"Refrigerate after opening; use a clean spoon.",how:"A teaspoon in tahini sauce, in a chicken marinade before roasting, or in a pasta sauce."}},
  {id:"bulbs-2",slug:"whole-black-garlic",gal:["assets/shot-bulbs.webp","assets/shot-macro.webp"],cat:["kitchen","gift"],bg:"#e8dfcf",img:"assets/shot-bulbs.webp",price:350,pair:["toast","butter","tahini"],
   ar:{n:"بصلتين كاملتين",s:"برطمان إزاز · حوالي ١٢٠ جم",d:"بصلتين بقشرهم. بتقشّر الفص وقت ما تحتاجه، وشكلهم حلو على السفرة.",u:"طبق جبن، تقديم، هدية",k:"مكان بارد وناشف.",how:"قشّر الفص وقت ما تحتاجه. حطّ بصلة مقطوعة نصين على طبق الجبن، وسيب الضيوف ياخدوا بنفسهم."},
   en:{n:"Two Whole Bulbs",s:"Glass jar · approx. 120 g",d:"Two bulbs in their skins. Peel cloves as you need them; beautiful on the table.",u:"Cheese boards, serving, gifting",k:"Cool, dry place.",how:"Peel cloves as you need them. Halve a bulb on a cheese board and let guests help themselves."}},
  {id:"gift-set",slug:"gift-set",gal:["assets/shot-gift.webp","assets/shot-cloves.webp","assets/shot-bulbs.webp"],cat:["gift"],bg:"#4f5236",img:"assets/shot-gift.webp",price:775,pair:["toast","pasta","chicken"],
   ar:{n:"طقم الهدية",s:"فصوص ١٠٠ جم + بصلتين · شنطة كرافت",tag:"هدية",d:"برطمانين في شنطة كرافت بيد حبل: واحد فصوص وواحد بصل كامل. لحد بيحب الأكل.",u:"هدية",k:"مكان بارد وناشف.",how:"الفصوص للطبخ، والبصل للتقديم."},
   en:{n:"The Gift Pair",s:"Cloves 100 g + two bulbs · kraft bag",tag:"Gift",d:"Two jars in a kraft bag with rope handles: one of cloves, one of whole bulbs. For someone who loves food.",u:"Gifting",k:"Cool, dry place.",how:"Cloves for cooking, bulbs for serving."}},
  {id:"daily-250",slug:"daily-pouch",gal:["assets/shot-pouch.webp","assets/shot-macro.webp"],cat:["daily"],bg:"#c9b48f",img:"assets/shot-pouch.webp",price:550,pair:["toast","tahini","salad"],
   ar:{n:"الكيس اليومي",s:"بصل كامل · ٢٥٠ جم",tag:"الأوفر",d:"بصل كامل بقشره في كيس بسوستة. للي بياكل فص أو اتنين كل يوم، وده أقل سعر للجرام عندنا.",u:"فص أو اتنين يوميًا",k:"اقفل الكيس كويس بعد كل استخدام.",how:"فص أو اتنين مع الفطار، زي ما هو أو على عيش."},
   en:{n:"Daily Pouch",s:"Whole bulbs · 250 g",tag:"Best value",d:"Whole bulbs in a resealable pouch. For a clove or two a day, and our lowest price per gram.",u:"A clove or two daily",k:"Reseal after each use.",how:"A clove or two with breakfast, as is or on bread."}},
];
KOJI.CHEF = [
  {id:"chef-cloves-1kg",chef:true,price:2800,ar:{n:"فصوص مقشّرة",s:"كيس حاجز · ١ كجم"},en:{n:"Peeled Cloves",s:"Barrier bag · 1 kg"}},
  {id:"chef-paste-500",chef:true,price:1200,ar:{n:"معجون",s:"عبوة · ٥٠٠ جم"},en:{n:"Paste",s:"Tub · 500 g"}},
  {id:"chef-bulbs-1kg",chef:true,price:2000,ar:{n:"بصل كامل",s:"١ كجم"},en:{n:"Whole Bulbs",s:"1 kg"}},
];

KOJI.FACTS = [["fact.sweet",7,1],["fact.umami",8,3],["fact.bals",7,0],["fact.acid",4,1],["fact.bite",1,9]];

KOJI.RECIPES = [
 {id:"toast",slug:"recipe-cheese-toast",min:5,cat:"breakfast",uses:"cloves-100",
  ar:{n:"توست جبنة وثوم أسود",t:"٥ دقايق",sv:"١",b:"أسهل طريقة تدوقه بيها أول مرة.",ing:["عيش توست أو فينو","شريحتين جبنة رومي أو شيدر","٢ فص ثوم أسود","رشة زعتر أو فلفل أسود"],st:["اهرس الفصوص بالشوكة وافردها على العيش.","حط الجبنة فوقها.","سخّنه في الفرن أو على طاسة لحد ما الجبنة تسيح.","رشّ الزعتر وكُل وهو سخن."],tip:"الثوم الأسود بيبقى طعمه زي مربى مالحة، فبيمشي مع أي جبنة."},
  en:{n:"Cheese Toast with Black Garlic",t:"5 min",sv:"1",b:"The easiest first taste.",ing:["Toast or a soft roll","2 slices of roumi or cheddar","2 black garlic cloves","Pinch of thyme or black pepper"],st:["Mash the cloves with a fork and spread on the bread.","Lay the cheese on top.","Warm in the oven or a pan until the cheese melts.","Finish with thyme and eat it hot."],tip:"Black garlic tastes like a savory jam, so it goes with any cheese."}},
 {id:"tahini",slug:"recipe-black-garlic-tahini",min:5,cat:"sauce",uses:"paste-100",
  ar:{n:"طحينة بالثوم الأسود",t:"٥ دقايق",sv:"كوب",b:"نفس طحينة البيت، بس بالثوم الأسود بدل الثوم العادي.",ing:["½ كوب طحينة","١ م.ص معجون ثوم أسود (أو ٣ فصوص مهروسة)","عصير ليمونة","ملح وكمون","مية ساقعة حسب القوام"],st:["اخلط الطحينة مع المعجون والليمون.","ضيف المية بالتدريج وإنت بتقلّب لحد ما تبقى ناعمة.","تبّلها بالملح والكمون."],tip:"حلوة مع الشاورما والكفتة والسمك المشوي، ومن غير ريحة الثوم النية."},
  en:{n:"Black Garlic Tahini",t:"5 min",sv:"1 cup",b:"Everyday tahini sauce, made with black garlic instead of raw garlic.",ing:["½ cup tahini","1 tsp black garlic paste (or 3 mashed cloves)","Juice of 1 lemon","Salt and cumin","Cold water as needed"],st:["Mix the tahini with the paste and lemon.","Add water little by little, stirring, until smooth.","Season with salt and cumin."],tip:"Great with shawarma, kofta and grilled fish, without the raw-garlic bite."}},
 {id:"pasta",slug:"recipe-white-sauce-pasta",min:20,cat:"main",uses:"cloves-100",
  ar:{n:"مكرونة وايت صوص بالثوم الأسود",t:"٢٠ دقيقة",sv:"٢–٣",b:"الوايت صوص اللي بتعمله، بطعم أعمق.",ing:["٢٥٠ جم مكرونة","٢ م.ك زبدة","٢ م.ك دقيق","٢ كوب لبن","٣ فصوص ثوم أسود مهروسة","جبنة موتزاريلا أو رومي مبشورة","ملح وفلفل"],st:["اسلق المكرونة.","دوّب الزبدة وقلّب فيها الدقيق دقيقة.","ضيف اللبن بالتدريج وقلّب لحد ما يتقل.","ضيف الثوم الأسود والملح والفلفل.","اخلط المكرونة بالصوص، ورشّ الجبنة، ودخّلها الفرن ١٠ دقايق لو حابب."],tip:"ممكن تزوّد فراخ مشوية أو مشروم."},
  en:{n:"White-Sauce Pasta with Black Garlic",t:"20 min",sv:"2–3",b:"The white-sauce pasta you already make, with a deeper flavor.",ing:["250 g pasta","2 tbsp butter","2 tbsp flour","2 cups milk","3 mashed black garlic cloves","Grated mozzarella or roumi","Salt and pepper"],st:["Boil the pasta.","Melt the butter and cook the flour in it for a minute.","Whisk in the milk gradually until thick.","Stir in the black garlic, salt and pepper.","Toss with the pasta, top with cheese, and bake 10 minutes if you like."],tip:"Add grilled chicken or mushrooms."}},
 {id:"chicken",slug:"recipe-oven-chicken",min:45,cat:"main",uses:"paste-100",
  ar:{n:"فراخ في الفرن بالثوم الأسود",t:"٤٥ دقيقة",sv:"٤",b:"تتبيلة فراخ عادية، والثوم الأسود بيدّيها لون وطعم.",ing:["١ فرخة مقطّعة أو ١ كجم أوراك","٢ م.ك معجون ثوم أسود","٣ م.ك زيت","عصير ليمونة","ملح وفلفل وبابريكا","بصلة شرائح"],st:["اخلط المعجون مع الزيت والليمون والتوابل.","تبّل الفراخ وسيبها نص ساعة على الأقل.","افرد البصل في الصينية وحط الفراخ فوقه.","ادخلها فرن ٢٠٠ درجة حوالي ٤٠ دقيقة لحد ما تحمّر."],tip:"لو سبت التتبيلة طول الليل في التلاجة، الطعم بيدخل أكتر."},
  en:{n:"Oven Chicken with Black Garlic",t:"45 min",sv:"4",b:"A regular chicken marinade; black garlic adds colour and depth.",ing:["1 chicken in pieces or 1 kg thighs","2 tbsp black garlic paste","3 tbsp oil","Juice of 1 lemon","Salt, pepper, paprika","1 onion, sliced"],st:["Mix the paste with oil, lemon and spices.","Coat the chicken and rest at least 30 minutes.","Spread the onion in a tray and set the chicken on top.","Roast at 200 °C for about 40 minutes until browned."],tip:"Marinate overnight in the fridge for more flavor."}},
 {id:"butter",slug:"recipe-black-garlic-butter",min:5,cat:"sauce",uses:"cloves-100",
  ar:{n:"زبدة الثوم الأسود",t:"٥ دقايق",sv:"برطمان صغير",b:"للعيش السخن والستيك والبطاطس.",ing:["١٠٠ جم زبدة طرية","٤ فصوص ثوم أسود","رشة ملح","بقدونس مفروم (اختياري)"],st:["اهرس الفصوص بالشوكة.","اخلطها مع الزبدة والملح والبقدونس.","حطها في التلاجة نص ساعة."],tip:"افردها على عيش بلدي سخن، أو حط حتة فوق ستيك طالع من على النار."},
  en:{n:"Black Garlic Butter",t:"5 min",sv:"1 small jar",b:"For hot bread, steak and potatoes.",ing:["100 g soft butter","4 black garlic cloves","Pinch of salt","Chopped parsley (optional)"],st:["Mash the cloves with a fork.","Mix with the butter, salt and parsley.","Chill for 30 minutes."],tip:"Spread on warm baladi bread, or melt a knob over a steak off the heat."}},
 {id:"salad",slug:"recipe-salad-dressing",min:3,cat:"sauce",uses:"paste-100",
  ar:{n:"تتبيلة سلطة بالثوم الأسود",t:"٣ دقايق",sv:"طبق سلطة",b:"تتبيلة زيت وليمون، بطعم حلو ومالح.",ing:["٣ م.ك زيت زيتون","١ م.ك ليمون أو خل","½ م.ص معجون ثوم أسود","رشة ملح","½ م.ص عسل (اختياري)"],st:["حط كل حاجة في برطمان صغير.","اقفله ورجّه لحد ما يتخلط.","صبّه على السلطة قبل الأكل على طول."],tip:"حلوة مع الجرجير والطماطم، وسلطة الجبنة البيضا."},
  en:{n:"Black Garlic Salad Dressing",t:"3 min",sv:"1 salad",b:"Oil and lemon, sweet and savory.",ing:["3 tbsp olive oil","1 tbsp lemon or vinegar","½ tsp black garlic paste","Pinch of salt","½ tsp honey (optional)"],st:["Put everything in a small jar.","Close and shake until mixed.","Pour over the salad just before eating."],tip:"Lovely with rocket and tomato, or a white-cheese salad."}},
];

KOJI.FAQ = {
 ar:[["هو ثوم متعفّن أو مخمّر؟","لأ. مفيش بكتيريا ولا خميرة ولا فطر. اللون الأسود من تفاعل طبيعي بين السكر والبروتين في الثوم مع الحرارة الهادية والوقت (تفاعل ميلارد)، نفس اللي بيحصل للعيش وهو بيتحمّص. و«كوجي» اسم البراند بس، مش بنستخدم فطر الكوجي الياباني."],
  ["ريحته زي الثوم العادي؟","لأ، أهدى بكتير. الحدة بتتكسر في التعتيق، وطعمه بيبقى أقرب لتمر أو بلسميك."],
  ["أحفظه إزاي؟","العبوة المقفولة في مكان بارد وناشف. بعد الفتح في التلاجة. تاريخ الصلاحية مكتوب على العبوة."],
  ["الفرق بين الفصوص والمعجون والبصل؟","الفصوص مقشّرة وجاهزة للأكل والتقطيع. المعجون أسهل في الخلط مع الصوصات. والبصل الكامل بقشره، بتقشّره وقت ما تحتاجه، وشكله حلو كهدية."],
  ["ليه أغلى من الثوم العادي؟","الثوم بيخس جزء من وزنه في التعتيق، والتعتيق بياخد ٣ أسابيع. وإنت بتستخدم فص أو اتنين في الطبق، مش رأس كاملة."],
  ["الدفع والتوصيل؟","كاش عند الاستلام، أو إنستاباي، أو فودافون كاش. القاهرة والجيزة الأول، ومصاريف التوصيل بتتحدد حسب العنوان ونقولهالك قبل التأكيد."],
  ["أتابع طلبي إزاي؟","من صفحة «تتبّع طلبك» برقم الطلب ورقم الموبايل اللي طلبت بيه."],
  ["هل له فوايد صحية؟","فيه أبحاث كتير على الثوم الأسود، بس إحنا مش هنقول ادعاءات صحية من غير بيانات على منتجنا ومراجعة تنظيمية. بنبيعه كأكل حلو الطعم."]],
 en:[["Is it fermented or mouldy?","No. No bacteria, yeast or mould. The colour comes from a natural reaction between the garlic's sugars and amino acids under gentle heat over time (the Maillard reaction), the same one that browns toast. KOJI is our name; we don't use koji mould."],
  ["Does it smell like garlic?","Much softer. The sharpness breaks down during ageing, leaving something closer to dates or balsamic."],
  ["How do I store it?","Sealed: somewhere cool and dry. Once opened: the fridge. Best-before is printed on the pack."],
  ["Cloves, paste or bulbs?","Cloves are peeled and ready to eat or slice. Paste blends easily into sauces. Whole bulbs come in their skins; peel as you go, and they make a beautiful gift."],
  ["Why does it cost more than garlic?","Garlic loses part of its weight while ageing, and each lot takes three weeks. And you use a clove or two, not a whole head."],
  ["Payment and delivery?","Cash on delivery, InstaPay or Vodafone Cash. Cairo and Giza first; delivery is quoted by address before you confirm."],
  ["How do I track my order?","On the Track order page, with your order number and the mobile you ordered with."],
  ["Is it a health food?","There's a lot of research on black garlic, but we won't make health claims without data on our own product and regulatory review. We sell it because it tastes extraordinary."]]
};

KOJI.LEGAL = {
 privacy: {
  updated: ["آخر تحديث: ٧ أكتوبر ٢٠٢٦", "Last updated: 7 October 2026"],
  ar: [
   ["بنجمع إيه", "لما تطلب: اسمك، ورقم موبايلك، وعنوانك، والمنتجات اللي طلبتها، وأي ملاحظة بتكتبها. ولما مطعم يطلب عينة: اسم المطعم، ودورك، والطبق، والكمية اللي متوقع تستخدمها."],
   ["بنستخدمها في إيه", "عشان نأكد طلبك ونوصّله ونكلمك بخصوصه، وعشان نرتّب عينة المطعم. مش بنبعتلك إعلانات من غير ما توافق."],
   ["بتتخزن فين", "في قاعدة بيانات على Supabase (سيرفرات في فرانكفورت، ألمانيا). اللي يقدر يشوفها فريق كوجي بس، بتسجيل دخول."],
   ["مين بيشوفها كمان", "مندوب التوصيل بياخد اسمك ورقمك وعنوانك عشان يوصّل الطلب. غير كده، مش بنبيع ولا بنشارك بياناتك مع حد."],
   ["الكوكيز", "مفيش كوكيز إعلانات ولا تتبّع. المتصفح بيحفظ سلتك واللغة اللي اخترتها على جهازك بس."],
   ["حقك", "تقدر تطلب نسخة من بياناتك أو تمسحها في أي وقت، بإيميل على العنوان اللي تحت. بنحتفظ بسجل الطلبات طول ما هو مطلوب للحسابات."],
  ],
  en: [
   ["What we collect", "When you order: your name, mobile number, address, the items you ordered and any note you add. When a restaurant requests a trial: the venue, your role, the dish and your estimated usage."],
   ["Why", "To confirm, deliver and contact you about your order, and to arrange restaurant trials. We don't send you marketing without your consent."],
   ["Where it's stored", "In a Supabase database (servers in Frankfurt, Germany). Only the KOJI team can access it, behind a login."],
   ["Who else sees it", "The courier receives your name, number and address to deliver your order. Otherwise we never sell or share your data."],
   ["Cookies", "No advertising or tracking cookies. Your browser keeps your bag and language choice on your own device."],
   ["Your rights", "You can ask for a copy of your data or ask us to delete it at any time by email. We keep order records for as long as accounting requires."],
  ]},
 terms: {
  updated: ["آخر تحديث: ٧ أكتوبر ٢٠٢٦", "Last updated: 7 October 2026"],
  ar: [
   ["الطلب المسبق", "إحنا بنعتّق على دفعات صغيرة، فكل طلب بيتسجل كطلب مسبق. بنكلمك نأكد ميعاد التسليم ومصاريف التوصيل، والطلب مش بيتأكد غير بعد المكالمة دي."],
   ["الأسعار", "الأسعار بالجنيه المصري. السعر اللي بيتحسب هو السعر وقت ما طلبت، ولو اتغيّر قبل التأكيد هنقولك وإنت تقرر."],
   ["التوصيل", "بنوصّل القاهرة والجيزة الأول، وباقي المحافظات بالاتفاق. مصاريف التوصيل بتتحدد حسب العنوان، وبنقولهالك قبل التأكيد."],
   ["الدفع", "كاش عند الاستلام، أو إنستاباي، أو فودافون كاش بعد ما نأكد الطلب. مفيش أي دفع قبل التأكيد."],
   ["الإلغاء", "تقدر تلغي الطلب ببلاش في أي وقت قبل ما يخرج للتوصيل. كلمنا أو ابعت إيميل برقم الطلب."],
   ["الاستبدال والاسترجاع", "الثوم الأسود أكل، فمش بنقدر نرجّع عبوة اتفتحت. بس لو الطلب وصلك فيه كسر، أو العبوة مفتوحة، أو المنتج شكله أو ريحته مش طبيعيين، ابعتلنا صورة ورقم الطلب خلال ٤٨ ساعة من الاستلام، وهنبدّله أو نرجّعلك فلوسك."],
   ["المنتج", "ثوم أسود، مكوّن واحد: ثوم. ده أكل، مش علاج ولا مكمّل غذائي. احفظه في مكان بارد وناشف، وبعد الفتح في التلاجة."],
  ],
  en: [
   ["Pre-orders", "We age in small lots, so every order is placed as a pre-order. We call you to confirm the delivery date and fee; the order is only confirmed after that call."],
   ["Prices", "Prices are in Egyptian pounds. The price at the time you ordered applies; if it changes before confirmation we'll tell you and you decide."],
   ["Delivery", "Cairo and Giza first, other governorates by arrangement. The delivery fee depends on your address and is quoted before confirmation."],
   ["Payment", "Cash on delivery, InstaPay or Vodafone Cash after we confirm the order. No payment before confirmation."],
   ["Cancellation", "Cancel free of charge any time before the order leaves for delivery. Call us or email your order number."],
   ["Returns", "Black garlic is food, so we can't take back an opened pack. But if your order arrives broken, unsealed, or looks or smells wrong, send a photo and your order number within 48 hours of delivery and we'll replace it or refund you."],
   ["The product", "Black garlic, one ingredient: garlic. It's food, not medicine or a supplement. Store somewhere cool and dry; refrigerate after opening."],
  ]},
};
